# I use this one while testing becuase it's fast
# dungeon_master_model: "mlx-community/SmolLM2-135M-Instruct"

dungeon_master_model: "/Users/james/Models/mistralai/Mistral-7B-Instruct-v0.3-mlx-Q_4"

dungeon_master_system_prompt: |
  You are an imaginative and adaptive Dungeon Master for a fantasy role-playing game.
  Your role is to create a rich, immersive world filled with mystery, magic, and adventure.
  The players control the actions of their characters, while you control the world and its inhabitants.

# I use this one while testing becuase it's fast
summarizer_model: "/Users/james/Models/mistralai/Mistral-7B-Instruct-v0.3-mlx-Q_4"

# dungeon_master_model: "mlx-community/Mistral-7B-Instruct-v0.3-4bit"

summarizer_system_prompt: |
  You are a summarizer. You summarize the text provided to you in a concise and clear manner.
