game_master_model:
    model_path: "Desmon2D/Wayfarer-12B:Q8_0"
    model-args:
      num_ctx: 32768
      temperature: 0.8
      min_p: 0.025
      repeat_penalty: 1.05

fact_extractor_model:
    model_path: "llama3.2:3b-instruct-q4_K_M"

scene_note_taker_model:
    model_path: "llama3.2:3b-instruct-q4_K_M"

