from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from typing import List

from langchain.output_parsers import PydanticOutputParser, RetryOutputParser
from langchain_ollama.llms import OllamaLLM

PROMPT_TEMPLATE = """
You are an AI assistant designed to generate realistic training data for keeping track of a table top role-playing game (TTRPG) campaign.
This training data will be used to train an AI assistant known as the Chronicler, which will help game masters keep track of their campaigns.
The Chronicler will take take the last player and dungeon master utterances and create scene notes based on them.
Your task is to generate examples for the Chronicler to learn from.

You will generate a player utterance and a game master utterance that could be said during a TTRPG campaign and then generate scene notes
you would expect to be created or updated based on the player and game master utterances.

########
Instructions:

Generate a player utterance that could be said during a TTRPG campaign.
Generate a game master utterance that could be said during a TTRPG campaign.
Create scene notes based on the player and game master utterances.

########
Important Notes:

Use proper names or nouns whenever possible for characters, locations, and items.
Never make assumptions or infer information that is not explicitly stated by the player or dungeom master in the scene notes.

########
Examples:
{examples}

########
The only thing returned should be returned in a json object in this format:
{format_instructions}

########
Now, generate and example game master utterance and create new scene notes based on the player and game master utterances.
"""

class SceneNotes(BaseModel):
    player_characters: List[str] = Field(
        description="List of player characters in the scene",
    )
    non_player_characters: List[str] = Field(
        description="List of non-player characters in the scene",
    )
    players_characters_location: List[str] = Field(
        description="The players location from largest to smallest (e.g. region, city, building, room)",
    )
    weather: List[str] = Field(
        description="The weather in the scene (e.g. sunny, rainy, snowy, foggy)",
    )
    time_of_day: str = Field(
        description="The time of day in the scene (e.g. morning, afternoon, evening, midnight, early morning)",
    )
    mood: List[str] = Field(
        description="The keywords that describe the mood of the scene (e.g. tense, relaxed, somber)",
    )

class ChroniclerOutput(BaseModel):
    scene_notes: SceneNotes = Field(
        description="Secene notes created or updated based on the player and game master utterances",
    )
    facts: List[str] = Field(
        description="List of independent facts extracted from the player and game master utterances. These facts must make sense without the context of the utterances, scene notes, or other facts. Facts should NEVER include minor details or transient information. Facts should be relevant to the campaign and the characters, locations, and items in it. Facts should be written in complete sentences. Each fact should have a high likelihood of being true a month from now. Each fact must include a proper name or noun for a person, place, or thing.",
    )


class ChroniclerInput(BaseModel):
    player_utterance: str = Field(
        description="Player utterance generated by the LLM",
    )
    game_master_utterance: str = Field(
        description="Game master utterance generated by the LLM",
    )

class ChroniclerTrainingEntry(BaseModel):
    chronicler_input: ChroniclerInput = Field(
        description="Input to the Chronicler",
    )
    chronicler_output: ChroniclerOutput = Field(
        description="Output from the Chronicler",
    )

examples = [
    ChroniclerTrainingEntry(
        chronicler_input=ChroniclerInput(
            player_utterance="My player's name is Creb. Lets have a viking themed adventure.",
            game_master_utterance="""You are Creb, a grizzled veteran of the Dreadwood Wars with a scarred face and battle-hardened frame. Years of surviving the bloodshed have left you with a keen instinct for danger and a sharp wit, though your haunted eyes reveal the dark memories that plague you.

You find yourself in the taproom of the Silver Chalice, a rough-and-tumble establishment nestled in the heart of Havenbrook. The air is thick with smoke and the smell of spilled ale, while the sounds of raucous laughter and clinking tankards fill the space. A weathered barkeep named Old Tom stands behind the counter, methodically wiping down mugs as he keeps an eye on the rowdy crowd. The room buzzes with gossip about recent raids from the Dreadwood and whispers of a growing cult activity in the outskirts of town.""",
        ),
        chronicler_output=ChroniclerOutput(
            scene_notes=SceneNotes(
                player_characters=["Creb"],
                non_player_characters=["Old Tom"],
                players_characters_location=["Havenbrook", "the Silver Chalice"],
                weather=[],
                time_of_day="",
                mood=[],
            ),
            facts=[
                "Creb is a player character with a scarred face, a battle-hardened frame, haunted eyes, a sharp wit, and a keen instinct for danger",
                "Creb is a veteran of the Dreadwood Wars",
                "The Silver Chalice is a rough-and-tumble establishment in Havenbrook",
                "Old Tom is the weathered barkeep of the Silver Chalice",
            ],
        ),
    ),
    ChroniclerTrainingEntry(
        chronicler_input=ChroniclerInput(
            player_utterance="My characters name is Cassie, a wood elf ranger, let start an adventure is a small wood elf village in the forrest.",
            game_master_utterance="""The morning sun filters through the canopy of ancient trees, dappling the forest floor with shifting patterns of light. In a small clearing surrounded by massive oaks and maples, the village of Brambletown nestles amidst the undergrowth. Wooden walkways connect rustic homes built into the trees, while moss-covered stone paths weave between them.

Cassie, a lithe wood elf ranger with copper skin and dark hair, descends a narrow trail leading from her elevated home. Her green eyes take in the familiar surroundings - the sweet scent of wildflowers mixes with woodsmoke from cooking fires. Other elves move purposefully about their daily tasks, some greeting Cassie with warm smiles while others remain absorbed in their work.

The village center holds the Heart Tree, its massive trunk reaching skyward, where village elders gather to discuss matters. Nearby, children play in a cleared area while their parents work nearby, crafting bows and arrows or weaving baskets from supple branches. The village's quiet harmony is broken only by the calls of birds and the rustling of leaves.""",
        ),
        chronicler_output=ChroniclerOutput(
            scene_notes=SceneNotes(
                player_characters=["Cassie"],
                non_player_characters=[],
                players_characters_location=["Brambletown"],
                weather=[],
                time_of_day="",
                mood=[],
            ),
            facts=[
                "Cassie is a player character, a wood elf ranger with copper skin, dark hair, and green eyes",
                "Brambletown is a village in the forest with rustic homes built into trees, wooden walkways, and moss-covered stone paths",
                "The Heart Tree is a massive tree in the village center where village elders gather to discuss matters",
            ],
        ),
    ),
    ChroniclerTrainingEntry(
        chronicler_input=ChroniclerInput(
            player_utterance="Hi, I'm Raleigh Royal, my nick name is Albatross. Lets start a pirate themed adventure!",
            game_master_utterance="""The year is 1714 and you are the notorious pirate captain, Raleigh Royal, better known by your nickname "Albatross." Your reputation for ruthless efficiency and keen wit has earned you a place among the most feared names in the Caribbean.

You stand at the helm of the Swift Serpent, a sleek frigate flying your Jolly Roger, as it cuts through the azure waters off the coast of Tortuga. The salty spray splashes against your weathered face while your crew of hardened cutthroats performs their duties with practiced efficiency. On the horizon, you spot the distinctive sails of a merchant vessel, its cargo holds likely brimming with Spanish gold destined for the New World. The wind is at your back, and the promise of plunder fills the air.

Your First Mate, the weathered Irishman James "BlackJack" Sullivan, stands ready at your side, his scarred face twisted into a predatory grin as he watches the merchant ship draw closer. The rest of your crew bustles about their stations, checking weapons and preparing for what promises to be an exciting afternoon. The merchant vessel's captain has spotted you and is frantically trying to change course, but your superior speed and the wind at your back will allow you to intercept him within minutes.""",
        ),
        chronicler_output=ChroniclerOutput(
            scene_notes=SceneNotes(
                player_characters=["Raleigh \"Albatross\" Royal"],
                non_player_characters=["James \"BlackJack\" Sullivan"],
                players_characters_location=["the Carribbean", "off the coast of Tortuga", "on board the Swift Serpent"],
                weather=[],
                time_of_day="",
                mood=[],
            ),
            facts=[
                "Raleigh Royal is a player character, a notorious pirate captain known as \"Albatross\" with a reputation for ruthless efficiency and keen wit",
                "Raleigh Royal commands the Swift Serpent, a sleek frigate flying the Jolly Roger",
                "James \"BlackJack\" Sullivan is Raleigh Royal's First Mate, a weathered Irishman with a scarred face",
                "The Swift Serpent is a pirate ship",
            ],
        ),
    ),
]

model = OllamaLLM(model="mistral:7b-instruct")

def generate_llm_output():

    try:
        parser = PydanticOutputParser(pydantic_object=ChroniclerTrainingEntry)
        prompt = PromptTemplate(
            template=PROMPT_TEMPLATE,
            input_variables=["examples"],
            partial_variables={"format_instructions": parser.get_format_instructions()},
        )

        examplesStr = ""

        for example in examples:
            examplesStr += example.model_dump_json(indent=2) + "\n"

        chain = prompt | model | parser
        response  = chain.invoke({"examples": examplesStr})

        entry = response
        print(entry.model_dump_json(indent=2))
        return entry

    except Exception as e:
        print(e)
        return []


generate_llm_output()
