from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from typing import List

from langchain.output_parsers import PydanticOutputParser, RetryOutputParser
from langchain_ollama.llms import OllamaLLM

PROMPT_TEMPLATE = """
You are an AI assistant designed to generate realistic training data for keeping track of a table top role-playing game (TTRPG) campaign.
Your task is to create diverse, natural-sounding player and game master utterances that reflect what actually might be said during a campaign.
And then provide a list of stand alone facts that can be extracted from the utterance.

########
Instructions:

Generate a player utterance that could be said during a TTRPG campaign.
Generate a game master utterance that could be said during a TTRPG campaign.
Generate a list of stand alone facts that can be extracted from the utterance.

########
Important Notes:

Eact fact must be able to stand alone and be understood without the context of the utterance or other facts.

########
Example player utterance:
My character's name is Creb.

########
Example game master utterance:
Creb, a seasoned warrior aboard one of the longships, participates in the first raid on the farm of Lindisfarne, an island monastery off the coast of Northumbria. The raid occurs in 793 AD, though the exact date is disputed. The sun rises over the misty North Sea as Creb and his comrades row their sleek dragon-headed longship towards the shore. The monks of Lindisfarne would soon discover the terrifying reality of Viking incursions into Britain. Creb sharpens his sword, preparing for the violence to come, knowing that this day will be etched in history as the beginning of the Viking Age in England.

########
Example extracted facts:

Creb is the player's character
Creb is a seasoned warrior
Creb participated in the first raid on the farm of Lindisfarne
Lindisfarne is an island monastery off the coast of Northumbria
Lindisfarne was first raided in 793 AD, the exact date is disputed

########
Generate the output in the list of string format

{format_instructions}

########
Now, generate and example game master utterance and a list of stand alone facts that can be extracted from the utterance.
"""

class ChroniclerTrainingEntry(BaseModel):
    player_utterance: str = Field(
        description="Player utterance generated by the LLM",
        min_length=1
    )
    game_master_utterance: str = Field(
        description="Game master utterance generated by the LLM",
        min_length=1
    )
    facts: List[str] = Field(
        description="List of standalone facts generated by the LLM",
        min_items=1
    )

model = OllamaLLM(model="mistral:7b-instruct-v0.3-q4_0")

def generate_llm_output():

    try:
        parser = PydanticOutputParser(pydantic_object=ChroniclerTrainingEntry)
        prompt = PromptTemplate(
            template=PROMPT_TEMPLATE,
            partial_variables={"format_instructions": parser.get_format_instructions()},
        )


        chain = prompt | model | parser
        response  = chain.invoke({})

        entry = ChroniclerTrainingEntry(
            player_utterance=response.player_utterance,
            game_master_utterance=response.game_master_utterance,
            facts=response.facts
        )

        print(entry)
        return entry

    except Exception as e:
        print(e)
        return []


generate_llm_output()
